[build]
  command = "NEXT_PUBLIC_BASE_PATH=/offshore-portal npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/offshore-portal/index.html"
  status = 200
